### ISSUE TITLE
Possible additional reference for your CodeLM security survey

### ISSUE THREAD

**Issue by jc-ryan** [wssun/TiSE-LM4Code-Security#2]
Dear authors,

This is a truly comprehensive survey! It systematically reviews the security vulnerabilities of code large language models.

I noticed that in the section on Backdoor Attacks on CodeLMs, our team's related work published in 2023 could be relevant. Our research, TrojanSQL, successfully demonstrated SQL injection attacks through backdoor mechanisms against natural language interfaces to databases, providing new insights into the security aspects of NL2SQL systems.

[(Zhang et al., EMNLP 2023) TrojanSQL: SQL Injection against Natural Language Interface to Database](https://aclanthology.org/2023.emnlp-main.264/)

Thank you again for your contribution in synthesizing knowledge in this field.

Best regards,

Jinchuan

**Comment by wssun** [comment]
Dear Jinchuan,

Thank you very much for your kind words and for bringing TrojanSQL (Zhang et al., EMNLP 2023) to our attention. Your work provides valuable insights into backdoor mechanisms, particularly within NL2SQL systems, and is indeed highly relevant to the discussion on backdoor attacks in our survey.

We have now added TrojanSQL to the list of papers in the repository and will ensure it is discussed in detail in the next revision of our manuscript.

Thank you once again for sharing your work and for contributing to the broader discourse on CodeLM security.

Best regards,
Weisong, on behalf of the authors

**Comment by jc-ryan** [comment]
Ok, thanks a lot !
